- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: arxiv:2403.12451
  image: images/insight.png
  description: ICML 2024 (Spotlight, top 3.5%)
  buttons:
    - type: website
      link: https://ins-rl.github.io/
  tags:
    - llm
    - neural-symbolic

- id: doi:10.1609/aaai.v37i10.26444
  image: images/digits.png
  buttons:
    - type: source
      link: https://github.com/sbx126/NToC
  tags:
    - deep learning
    - neural-symbolic

